version: '3.8'

services:
  postgres:
    image: postgres:15
    container_name: matchdb
    restart: always
    environment:
      POSTGRES_DB: matchdb
      POSTGRES_USER: matchuser
      POSTGRES_PASSWORD: matchpass
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
